### ISSUE TITLE
Error: Unable to import module 'process_cert_manager_mail': No module named requests

### ISSUE THREAD

**Issue by nford** [ImmobilienScout24/aws-cf-verified-ssl-certificate#2]
Lambda can't find the Requests module which isn't bundled in your repo. I'm not a Python expert - is it expected to be installed already in Lambda?

**Comment by heroldus** [comment]
Hi @nford,

the `requests` package is a python package which is downloaded and added to the final zip file during the build (see [`deploy.sh` line 14](https://github.com/ImmobilienScout24/aws-cf-verified-ssl-certificate/blob/master/deploy.sh#L14) ). If you use `s3://is24-infrastructure-public/cloudformation/verified-ssl-certificate/lambda_functions.zip` it's already included.

Hope this helps.

**Comment by nford** [comment]
It does indeed, thank you. Since I'm integrating this as a nested stack within a larger deployment I hadn't looked at the deploy.sh file because judging by name I assumed it wasn't relevant for my case. Thanks again.
