### ISSUE TITLE
how it works

### ISSUE THREAD

**Issue by mvayngrib** [ImmobilienScout24/aws-cf-verified-ssl-certificate#5]
first off, thanks for making this, it looks like just what i need!

do you have a short description of the moving parts? I understand the problem: amazon sends an email to admin@domain and a bunch of others, making confirmation a manual process. I'd like to understand the solution better.

**Comment by mirkoprescha** [comment]
the readme.md is updated.

your right. The confirmation process is done in `process_cert_manager_mail` by parsing the amazon verification email, extracting the approval link and posting a http request for it.

**Comment by mvayngrib** [comment]
@mirkoprescha thanks, that clears things up!
